GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/gbp
###
GET http://localhost:8082/posts/1234/comments/56789
###
GET http://localhost:8082/currencies?min_value=0.001
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/abcd
###
GET http://localhost:8082/users/search?gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?age=49
Authorization: LetMeIn
###
GET http://localhost:8082/users/search
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Blog on Manali",
    "author": [
        {
            "fullName": "jim corbett",
            "email": "jim@bbc.com",
            "image": "http://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg"
        }
    ]
}
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/6789291c8b48ca9159c1a76f
###
DELETE http://localhost:8082/blogs/6789291c8b48ca9159c1a76f
###
PATCH http://localhost:8082/blogs/678931c182922d7d0e401c72
Content-Type: application/json

{
    "author": ["alan shearer", "isak"]
}