GET http://localhost:8082/currencies
###
GET http://localhost:8082/currencies/gbp
###
GET http://localhost:8082/posts/1234/comments/56789
###
GET http://localhost:8082/currencies?min_value=0.001
###
GET http://localhost:8082/users
Authorization: LetMeIn
###
GET http://localhost:8082/users/abcd
###
GET http://localhost:8082/users/search?gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?gender=male
Authorization: LetMeIn
###
GET http://localhost:8082/users/search?age=49
Authorization: LetMeIn
###
GET http://localhost:8082/users/search
###
POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Blog on Edinburgh",
    "author": [
        {
            "fullName": "Paras Khandelwal",
            "email": "paras@jpmc.com"
        }
    ]
}
###
GET http://localhost:8082/blogs
###
GET http://localhost:8082/blogs/678a87dc8faffba35d7fb4f1
###
DELETE http://localhost:8082/blogs/678a87dc8faffba35d7fb4f1
###
PATCH http://localhost:8082/blogs/67893733adee8df6eb86d479
Content-Type: application/json

{
    "author": [
      {
        "fullName": "Kaoru Mitoma",
        "email": "mitoma@bfc.com"
      }
    ]
}
###
GET http://localhost:8082/blogs/search?title=blog&author=mitoma@bfc.com
###
GET http://localhost:8082/blogs/search?title=Blog%20on%20Liverpool
###
GET http://localhost:8082/blogs/search?title=chelsea
###
GET http://localhost:8082/blogs/search?author=mitoma@bfc.com
###
GET http://localhost:8082/blogs/search